include: package:flutter_lints/flutter.yaml

linter:

  rules:
    lines_longer_than_80_chars: false
    public_member_api_docs: false
    directives_ordering: true
    sort_pub_dependencies: true
    avoid_relative_lib_imports: true
    prefer_relative_imports: true